### ISSUE TITLE
Kuara 8.0-3-H (Kopp) modbus by LAN problems

### ISSUE THREAD

**Issue by EricSoft4** [rsaemann/HA-FoxESS-H3-Modbus#2]
Hello,

I hope someone can help me with the following problem.

I have an inverter (Kuara 8.0-3-H) from Kopp, brand label Foxess.
I'm trying to read out the modbus here via modbus tcp Node Red.
Modbus connects to the inverter but keeps giving an error when I try to read on address 31000.

I have read that there are problems with LAN and the H3 converters, regarding modbus and port 502.
But it seems that my inverter does have the port open (connect), only that the addresses are wrong.

![node red node](https://user-images.githubusercontent.com/87763969/207052379-5b512169-29fc-41ae-baec-a01d3468b64c.png)
![node red modbus read node](https://user-images.githubusercontent.com/87763969/207053226-2b4af860-ad34-429d-ba2d-440a4c6a2ffb.png)
![node red client node](https://user-images.githubusercontent.com/87763969/207053253-429fc610-9aab-498f-b951-4c82322d0d03.png)
![node red error](https://user-images.githubusercontent.com/87763969/207052556-9bb7b98c-7436-4cf3-a162-ddbd31abe6f6.png)

**Comment by rsaemann** [comment]
Maybe there are different addresses for serial and for LAN access, like it is the case for H1 inverters. ([For H1: 11000 via RS485 is equivalent to 31000 via LAN](https://github.com/StealthChesnut/HA-FoxESS-Modbus/wiki/Data-Register-Reference---H1-AC1) ).
My advice for you is to go through the registers in steps of 1000 and query only 4 registers (not 32). The result is empty if the requested range is larger than the defined length.

**Comment by EricSoft4** [comment]
I tested on all addresses in steps of 100, from 0 to 65600.
At FC4 I found 100 addresses starting at 300.
At FC 3 100 addresses starting at 400.
These addresses all have the value 0.
It seems that addresses have been created but not linked.

**Comment by EricSoft4** [comment]
I heard from Foxess that LAN is not possible with this inverter. 
I have to work with RS485. So i will check that out.

**Comment by revajcagro** [comment]
This is the official statement from foxess about LAN port now: Our Ethernet port is not active. The hardware PCB is there, but the software has not been developed yet. The software will be available sometime next year. You cannot use this port for Ethernet communication.

**Comment by EricSoft4** [comment]
Okay thanks, then I'll just have to wait for that and try again with the new software if possible.
